# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Analytics_Recommender_pb2 as Analytics__Recommender__pb2


class AnalyticsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUploadedReviews = channel.unary_stream(
        '/Paitoo.Analytics/GetUploadedReviews',
        request_serializer=Analytics__Recommender__pb2.Query.SerializeToString,
        response_deserializer=Analytics__Recommender__pb2.Review.FromString,
        )
    self.GetLikedReviews = channel.unary_stream(
        '/Paitoo.Analytics/GetLikedReviews',
        request_serializer=Analytics__Recommender__pb2.Query.SerializeToString,
        response_deserializer=Analytics__Recommender__pb2.Liked_Review.FromString,
        )
    self.GetFollowedRestaurants = channel.unary_stream(
        '/Paitoo.Analytics/GetFollowedRestaurants',
        request_serializer=Analytics__Recommender__pb2.Query.SerializeToString,
        response_deserializer=Analytics__Recommender__pb2.Follow_Restaurant.FromString,
        )
    self.GetOpenedDish = channel.unary_stream(
        '/Paitoo.Analytics/GetOpenedDish',
        request_serializer=Analytics__Recommender__pb2.Query.SerializeToString,
        response_deserializer=Analytics__Recommender__pb2.Opened_Dish.FromString,
        )


class AnalyticsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUploadedReviews(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLikedReviews(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowedRestaurants(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOpenedDish(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnalyticsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUploadedReviews': grpc.unary_stream_rpc_method_handler(
          servicer.GetUploadedReviews,
          request_deserializer=Analytics__Recommender__pb2.Query.FromString,
          response_serializer=Analytics__Recommender__pb2.Review.SerializeToString,
      ),
      'GetLikedReviews': grpc.unary_stream_rpc_method_handler(
          servicer.GetLikedReviews,
          request_deserializer=Analytics__Recommender__pb2.Query.FromString,
          response_serializer=Analytics__Recommender__pb2.Liked_Review.SerializeToString,
      ),
      'GetFollowedRestaurants': grpc.unary_stream_rpc_method_handler(
          servicer.GetFollowedRestaurants,
          request_deserializer=Analytics__Recommender__pb2.Query.FromString,
          response_serializer=Analytics__Recommender__pb2.Follow_Restaurant.SerializeToString,
      ),
      'GetOpenedDish': grpc.unary_stream_rpc_method_handler(
          servicer.GetOpenedDish,
          request_deserializer=Analytics__Recommender__pb2.Query.FromString,
          response_serializer=Analytics__Recommender__pb2.Opened_Dish.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Paitoo.Analytics', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
